version: '3.8'

services:
  mysql:
    image: app
    container_name: galeria-app
    environment:
      MYSQL_DATABASE: galeria
      MYSQL_USER: Cvbarro
      MYSQL_PASSWORD: CvVtJp123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - galeria-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: galeria-app
    ports:
      - "80:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ibmec-galeria-cloud.mysql.database.azure.com:3306/galeria
      SPRING_DATASOURCE_USERNAME: Cvbarro
      SPRING_DATASOURCE_PASSWORD: CvVtJp123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    networks:
      - galeria-network

volumes:
  mysql_data:

networks:
  galeria-network:
